### ISSUE TITLE
fix links in lesson links

### ISSUE THREAD

**Issue by maneesha** [carpentries/usersguides#14]
The section on [not good starting points for demos](http://docs.carpentries.org/instructor_training/trainers_guide.html#not-good-starting-points-for-demos)
was copied and pasted from the lessons website.  The URLs include variables that break when they are on this site. 

Does anyone know if these URLs need to be hard coded or if there's a way to preserve the variables?

**Comment by maneesha** [comment]
Maybe @jduckles  @tracykteal  @ErinBecker can help?

**Comment by tracykteal** [comment]
Unless you can set a variable 'site.swc_pages' within the Readthedocs framework, I think it will need to be the full URL, like http://swcarpentry.github.io/shell-novice/01-intro/

**Comment by jduckles** [comment]
`({site.swc_pages}}`is largely to allow things to be found if hosted at https://software-carpentry.org or https://swcarpentry.github.io and is a Jekyll setting.

**Comment by ErinBecker** [comment]
Closed with 8018311
