### ISSUE TITLE
Process for Training Trainers document

### ISSUE THREAD

**Issue by maneesha** [carpentries/usersguides#16]
This lives in a [google doc](https://docs.google.com/document/d/14Zi_W9uk1wua2v3zy8um6oMCnvO41Qfo1KwStCA-hos/edit).

Should it stay as a google doc or move to this repo?

**Comment by ErinBecker** [comment]
It should move to this repo.

**Comment by maneesha** [comment]
Closing.
See http://docs.carpentries.org/topic_folders/instructor_training/trainers_training.html
