### ISSUE TITLE
I hand installed the userguide to docs.carpentries.org

### ISSUE THREAD

**Issue by jduckles** [carpentries/usersguides#3]
@maneesha I hand installed this on our static webserver (where software-carpentry.org) is hosted. 

http://docs.carpentries.org/toc.html

Steps
1. Add DNS A Record pointing to `docs.carpentries.org`
2. Configure nginx (webserver) to Virtual Host for `docs.carpentries.org` (see below)
3. `git clone` the repo and run `make html`, then copy to webroot for `docs.carpentries.org`

```
pip install Sphinx sphinx_rtd_theme recommonmark
git clone https://github.com/carpentries/usersguides/
cd userguides
make html 
cp _site/html/* /home/data/docs.carpentries.org
```

nginx config:

```
server {
	listen 80;
	listen [::]:80;

	keepalive_timeout 70;

	root /home/data/docs.carpentries.org/;

	server_name docs.carpentries.org;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}
}
```

**Comment by maneesha** [comment]
Thanks @jduckles  for setting this up and including an explanation of how this all works.  I saw your issue #4 to automatically build updates. In the meantime how should we push updates?

**Comment by maneesha** [comment]
@jduckles  Should we include this in the "about" section so we can close this issue?

**Comment by jduckles** [comment]
I already added the dependencies to the readme. The rest is kind of host specific, so I'll just close this issue.
