### ISSUE TITLE
Redirect base URL to toc

### ISSUE THREAD

**Issue by maneesha** [carpentries/usersguides#5]
How do you redirect http://docs.carpentries.org/  to http://docs.carpentries.org/toc.html ?

**Comment by jduckles** [comment]
Can you rename `toc.rst` to `index.rst`.  If not, create an index.html that has contains `<meta http-equiv="refresh" content="0; http://docs.carpentries.org/toc.html>`

**Comment by maneesha** [comment]
Fixed with https://github.com/carpentries/usersguides/commit/8b67c492ab948ef4e950d30a411600240a07294e
