### ISSUE TITLE
Broken link to host checklist

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/usersguides#54]
In the Discussion Sessions section, the link to the host checklist is broken. It directs to http://docs.carpentries.org/topic_folders/mentoring/checklists-discussion-sessions.md instead of https://github.com/carpentries/mentoring/blob/master/checklists-discussion-sessions.md.

Same with the link to the blogpost template towards the end of the section (currently points to http://docs.carpentries.org/topic_folders/mentoring/template-blog-about-debriefing-session.md)

**Comment by tobyhodges** [comment]
I guess you might want to link to checklists in the handbook itself, instead of the mentoring repo?

**Comment by maneesha** [comment]
Yes, the checklists should go in the handbook itself.  I'll work on that.  Thanks!

**Comment by tobyhodges** [comment]
Fair enough. I guess that, to begin with, a lot of this was ported across from our docs at carpentries/mentoring? There seems to be a lot of redundancy between the checklist and the discussion sessions section, so we can cut a lot of that out. I'm happy to fix this in a PR too.

**Comment by tobyhodges** [comment]
I have addressed the redundancy in #63

**Comment by maneesha** [comment]
closing with https://github.com/carpentries/usersguides/pull/63
