### ISSUE TITLE
More intro needed for discussion sessions

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/usersguides#55]
I'm not sure about the target audience for these docs, but I would like to see some content in the section on discussion sessions that encourages people to host the sessions. It currently says that a host is a member of the mentoring subcommittee. That's not _strictly_ true: a few of our lovely hosts seldom/never attend a subcommittee meeting, which is how we define membership.

More importantly, we currently lack a clear statement that new hosts (and members of the subcommittee) are warmly welcomed. I'd like to add a short blurb at the beginning of the section (or somewhere else if more appropriate), encouraging people to sign up to host and/or observe a session hosted by someone else, and to come along to a mentoring subcommittee meeting (open to all!) if they have any questions. 

Happy to submit a PR for this, if you approve.

**Comment by maneesha** [comment]
A PR towards this would be great @tobyhodges !
